### ISSUE TITLE
Proxy Class Generator Issues

### ISSUE THREAD

**Issue by DanielFatkic** [codingjungle/toolbox#29]
**Describe the bug**
I've noticed 2 issues with IPS 4.6.5 and the current dev branch.

1. The ACP menu doesn't link to the proxy rebuild page. I'm not sure if it's intentional or not, but I also couldn't find any JS controller or module which would handle this .Clicking on the link isn't initialising anything for me.
2. Opening the module=proxy&controller=proxy class results in:

```
Undefined array key 'complete' 116 #0 /Users/df/proj/applications/toolbox/modules/admin/proxy/proxy.php(116): Whoops\Run->handleError(2, 'Undefined array...', '/Users/danielfa...', 116)
#1 /Users/df/proj/system/Helpers/MultipleRedirect/MultipleRedirect.php(93): IPS\toolbox\modules\admin\proxy\_proxy::IPS\toolbox\modules\admin\proxy\{closure}(Array)
#2 /Users/df/proj/init.php(902) : eval()'d code(31): IPS\Helpers\_MultipleRedirect->__construct(Object(IPS\Http\Url\Internal), Object(Closure), Object(Closure), true)
#3 /Users/df/proj/applications/toolbox/modules/admin/proxy/proxy.php(140): IPS\Helpers\toolbox_hook_MultiRedirect->__construct(Object(IPS\Http\Url\Internal), Object(Closure), Object(Closure))
#4 /Users/df/proj/system/Dispatcher/Controller.php(101): IPS\toolbox\modules\admin\proxy\_proxy->manage()


```

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: safari
 - IPS Version: 4.6.5

**Comment by codingjungle** [comment]
this is fixed in the latest commit.

I've moved away from MultipleRedirect method in favor of a ajax initiated call. 

the problem was, i had the JS loading only if the profiler was being used (cause originally the button that did the ajax call was found on the profiler, but it worked so well i decided to change the acp menu one to the ajax call as well. however since i use the profiler, i never noticed the JS wasn't loaded). 
![Screen Shot 2021-08-08 at 9 01 41 AM](https://user-images.githubusercontent.com/3393297/128634694-163c09d3-eea4-437e-a377-c1ee8737872f.png)
